name: Upload OpenAPI spec to Stainless

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stainless-api/upload-openapi-spec-action@5b777c96ea953566047305022ca7d02586f5e5c8
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'openapi.yml'
          project_name: 'meorphis-test'
          commit_message: 'my extremely cool feature'
